cc_test(
  name = "basic_syntax",
  size = "small",
  srcs = ["syntax.cc"],
  deps = [
      "@googletest//:gtest_main",
    ],
)

cc_test(
  name = "rvo",
  size = "small",
  srcs = ["rvo.cc"],
  deps = [
      "@googletest//:gtest_main",
    ],
)

cc_test(
  name = "template",
  size = "small",
  srcs = ["template.cc"],
  deps = [
      "//example/common:type_name",
      "@googletest//:gtest_main",
    ],
)

cc_test(
  name = "lambda",
  size = "small",
  srcs = ["lambda.cc"],
  deps = [
      "@googletest//:gtest_main",
    ],
)