cc_test(
  name = "basic_syntax",
  size = "small",
  srcs = ["syntax.cc"],
  deps = [
      "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
  name = "rvo",
  size = "small",
  srcs = ["rvo.cc"],
  deps = [
      "@com_google_googletest//:gtest_main",
    ],
)