cc_test(
  name = "uvw_test",
  size = "small",
  srcs = ["uvw_test.cc"],
  linkopts = ["-undefined error"],
  deps = [
      "@com_github_uvw//:uvw",
      "@com_google_googletest//:gtest_main",
    ],
)