cc_test(
  name = "string_view_test",
  size = "small",
  srcs = ["string_view_test.cc"],
  deps = [
      "@com_google_googletest//:gtest_main",
      "@com_google_absl//absl/strings:strings",
    ],
)