
# 定义包的可见性
package(
    default_visibility = [
        "//visibility:public"
    ],
)
cc_library(
  name = "type_name",
  # visibility = ["//visibility:public"] 还可以在这里单独定义target的可见性
  srcs = ["type_name.h"],
  deps = [],
)